name: Publish Package
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Deno
        uses: denoland/setup-deno@v2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - name: Test
        run: deno test -RE
      - name: TypeCheck
        run: deno check src

      - name: Update npm
        run: npm install -g npm@latest
      - name: Publish to npm
        run: npm publish
